version: '3'
services:
  api:
    build:
        context: ./
        dockerfile: ./Dockerfile
    command: python manage.py runserver 0.0.0.0:8080
    depends_on:
      - postgres
    volumes:
      - ./:/usr/src/app
    ports:
      - "8080:8080"
    environment:
      - DATABASE_URL=postgres://postgres@postgres:5432/matsbymatts
      - ENVIRON=local
      - DJANGO_SETTINGS_MODULE=api.settings

  postgres:
    image: postgres:11.2-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: matsbymatts
