# Generated by Django 2.2.1 on 2019-05-06 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='description',
        ),
        migrations.RemoveField(
            model_name='item',
            name='part_number',
        ),
        migrations.AddField(
            model_name='item',
            name='color',
            field=models.CharField(choices=[('RED', 'red'), ('ORANGE', 'orange'), ('YELLOW', 'yellow'), ('GREEN', 'green'), ('BLUE', 'blue'), ('INDIGO', 'indigo'), ('VIOLET', 'violet')], default='RED', max_length=16),
        ),
        migrations.AddField(
            model_name='item',
            name='name',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
    ]
