# Generated by Django 2.2.1 on 2019-05-07 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_auto_20190506_0215'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='description',
            field=models.CharField(blank=True, db_index=True, default='', max_length=128),
        ),
    ]
