# Generated by Django 2.2.1 on 2019-05-08 02:39

import django.contrib.postgres.indexes
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_auto_20190507_2133'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='item',
            index=django.contrib.postgres.indexes.GinIndex(fields=['name'], name='name_trigram_index', opclasses=['gin_trgm_ops']),
        ),
    ]
