# Generated by Django 2.2.1 on 2019-05-08 03:44

import django.contrib.postgres.indexes
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_auto_20190507_2133'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='inventor',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AddIndex(
            model_name='item',
            index=django.contrib.postgres.indexes.GinIndex(fields=['inventor'], name='inventor_trigram_index', opclasses=['gin_trgm_ops']),
        ),
    ]
